### ISSUE TITLE
WebKit and NTFS do not display proper y-m-d

### ISSUE THREAD

**Issue by jdmoore** [pstirparo/utils#1]
Given the epoch returned for each value as:
```
Epoch Time input to be converted:  0
Unix:   1970-01-01 00:00:00 UTC
COCOA:  2001-01-01 00:00:00 UTC
FAT:    1980-01-01 00:00:00 UTC
HFS+:   1904-01-01 00:00:00 UTC
WebKit: 1601-01-01 00:00:00 UTC
NTFS:   1601-01-01 00:00:00 UTC
```
The WebKit and NTFS results do not display the proper result:
```
Epoch Time input to be converted:  1511178186
Unix:   2017-11-20 11:43:06 UTC
COCOA:  2048-11-20 11:43:06 UTC
FAT:    2027-11-20 11:43:06 UTC
HFS+:   1951-11-20 11:43:06 UTC
WebKit: 1601-01-01 00:25:11 UTC
NTFS:   1601-01-01 00:02:31 UTC
```

**Comment by pstirparo** [comment]
Hi jdmoore,

thanks for reporting, but could you be more specific? I don't understand exactly the "since value showed in 0, then output of 1511178186 is wrong"
Is that a timestamp value related to WebKit or NTFS? If so, what is suppose to refer to? 
To be honest it does not look like one of those but a standard 32bit timestamp. Let's take WebKit for example, it's a 64-bit value for microseconds since Jan 1, 1601 00:00 UTC. To give you an example, current WebKit epoch time value is 13124138051000000, substantially bigger value.
I also compared my output f your value, 1511178186 , with the well known http://www.epochconverter.com/webkit online converter and we get same output.
If you could specify a bit more it would be great.
thanks again

**Comment by jdmoore** [comment]
pstirparo,

Apologies, I overlooked the conversion of my input into microseconds. I mistakenly assumed that the tool used the same units for input to generate all of the timestamps and entered seconds as input instead of microseconds.

Great work on this tool and thank you for creating it!
